export const category = {
  success: true,
  msg: "Successfully fetched categories",
  categories: [
    { categoryId: 1, name: "Electronics" },
    { categoryId: 2, name: "Fashion" },
    { categoryId: 3, name: "Mobiles" },
    { categoryId: 4, name: "Appliances" },
    { categoryId: 5, name: "Groceries" },
    { categoryId: 8, name: "Household" },
    { categoryId: 11, name: "Movies" },
    { categoryId: 12, name: "RealEstate" },
    { categoryId: 13, name: "Household" },
    { categoryId: 14, name: "Bikes" },
    { categoryId: 15, name: "cycles" },
    { categoryId: 16, name: "cycles" },
    { categoryId: 17, name: "iphone" },
    { categoryId: 18, name: "iphone" },
    { categoryId: 19, name: "LED bulbs" },
    { categoryId: 20, name: "LED bulbs" },
    { categoryId: 21, name: "LED bulbs" },
    { categoryId: 22, name: "LED. bulbs" },
    { categoryId: 23, name: "Sunglasses" },
    { categoryId: 24, name: "Household" },
    { categoryId: 25, name: "Household" },
    { categoryId: 27, name: "home" },
  ],
};
